#version: '3.8'

services:
  server:
    image: golang:1.23-alpine
    container_name: a_studio_server
    volumes:
      - .:/server
    working_dir: /server/server
    ports:
      - "5000:5000"
    depends_on:
      - postgres_db
    entrypoint: ["go", "run", "cmd/astudio/main.go"]
    restart: always
    networks:
      - netcore-dev
  postgres_db:
    image: postgres:17.2
    container_name: postgres
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - ./server/.env # load env variables when the service is executed
    volumes:
      - ${HOST_DIR}:/var/lib/postgresql/data # Provided by ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
    - netcore-dev

networks:
  netcore-dev:
    name: netcore-dev #use the specified network name